# Generated by Django 5.0rc1 on 2023-12-31 08:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.upload_path
            ),
        ),
    ]
